// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Account struct {
	ID          string      `json:"id"`
	AccountType AccountType `json:"accountType"`
}

func (Account) IsEntity() {}

type User struct {
	ID       string     `json:"id"`
	Accounts []*Account `json:"accounts,omitempty"`
}

func (User) IsEntity() {}

type AccountType string

const (
	AccountTypeSavings  AccountType = "SAVINGS"
	AccountTypeChecking AccountType = "CHECKING"
	AccountTypeCredit   AccountType = "CREDIT"
)

var AllAccountType = []AccountType{
	AccountTypeSavings,
	AccountTypeChecking,
	AccountTypeCredit,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeSavings, AccountTypeChecking, AccountTypeCredit:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
